version: '3.3'
services:
  postgres-test:
    image: debezium/example-postgres:1.9
    container_name: postgres-test
    ports:
      - 8001:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ecommerce
