version: '3.3'
services:
  postgres:
    image: debezium/example-postgres:1.9
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ecommerce
    volumes:
      - ./sql/create-table-and-insert-data.sql:/docker-entrypoint-initdb.d/create-table-and-insert-data.sql
  zookeeper:
    image: wurstmeister/zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
  kafka:
    image: wurstmeister/kafka:latest
    restart: 'no'
    links:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
  kconnect:
    image: debezium/connect:1.9
    ports:
      - 8083:8083
    environment:
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses
      BOOTSTRAP_SERVERS: kafka:29092
    links:
      - zookeeper
      - postgres
    depends_on:
      - kafka
      - zookeeper
      - postgres
    volumes:
      - ./jars/debezium-scripting-2.4.0.Final.jar:/kafka/connect/debezium-connector-postgres/debezium-scripting-2.4.0.Final.jar
      - ./jars/groovy-jsr223-3.0.19.jar:/kafka/libs/groovy-jsr223-3.0.19.jar
      - ./jars/groovy-4.0.15.jar:/kafka/libs/groovy-4.0.15.jar
      - ./jars/groovy-json-4.0.15.jar:/kafka/libs/groovy-json-4.0.15.jar
      - ./jars/js-scriptengine-22.2.0.1.jar:/kafka/libs/js-scriptengine-22.2.0.1.jar
      - ./jars/js-23.0.1.jar:/kafka/libs/js-23.0.1.jar
